version: '3.4'
services: 
  mongo:
    container_name: cardinal-mongo
    image: mongo:latest
    ports: 
      - 3001:27017
    volumes:
      - cardinal-mongo:/data/db

volumes:
  cardinal-mongo:
    name: cardinal-mongo